# Generated by Django 4.1 on 2023-12-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_id', models.IntegerField()),
                ('pokemon_name', models.CharField(max_length=20)),
                ('pokemon_abilities', models.CharField(max_length=20)),
                ('pokemon_types', models.CharField(max_length=20)),
                ('pokemon_url', models.URLField(default='', max_length=300)),
            ],
        ),
    ]
