# Generated by Django 4.1 on 2023-12-18 18:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poketeam_bck', '0002_alter_pokemon_pokemon_abilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='pokemon_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, default=list, null=True, size=None),
        ),
    ]
