# Generated by Django 4.1.5 on 2024-01-03 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poketeam_bck', '0004_alter_pokemon_pokemon_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=30)),
            ],
        ),
    ]
