# Generated by Django 4.1.5 on 2024-01-04 14:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poketeam_bck', '0005_pokemontypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemontypes',
            name='double_damage_from',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='pokemontypes',
            name='double_damage_to',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='pokemontypes',
            name='half_damage_from',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='pokemontypes',
            name='half_damage_to',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='pokemontypes',
            name='no_damage_from',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='pokemontypes',
            name='no_damage_to',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='pokemontypes',
            name='pokemon_in_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, null=True, size=None),
        ),
    ]
