# Generated by Django 4.2.8 on 2024-12-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofilemodel',
            old_name='trainer_name',
            new_name='trainer_status',
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='pokemon_teams_created',
            field=models.IntegerField(default=0),
        ),
    ]
